package com.we.repay.dto.draw;

import java.util.Date;

import com.we.repay.dto.QueryReqDTO;

@SuppressWarnings("serial")
public class RandomDrawReqDTO extends QueryReqDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.rd_id
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Long rdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.name
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.number_code
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String numberCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.no_prefix_code
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Integer noPrefixCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.prize_level
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Short prizeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.prize_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Date prizeDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.crt_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Date crtDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.modify_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Date modifyDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.member_type
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Short memberType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.user_id
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.status
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.attribute1
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private Short attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.attribute2
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.attribute3
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.attribute4
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.attribute5
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_draw.attribute6
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    private String attribute6;

	public Long getRdId() {
		return rdId;
	}

	public void setRdId(Long rdId) {
		this.rdId = rdId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumberCode() {
		return numberCode;
	}

	public void setNumberCode(String numberCode) {
		this.numberCode = numberCode;
	}

	public Integer getNoPrefixCode() {
		return noPrefixCode;
	}

	public void setNoPrefixCode(Integer noPrefixCode) {
		this.noPrefixCode = noPrefixCode;
	}

	public Short getPrizeLevel() {
		return prizeLevel;
	}

	public void setPrizeLevel(Short prizeLevel) {
		this.prizeLevel = prizeLevel;
	}

	public Date getPrizeDtm() {
		return prizeDtm;
	}

	public void setPrizeDtm(Date prizeDtm) {
		this.prizeDtm = prizeDtm;
	}

	public Date getCrtDtm() {
		return crtDtm;
	}

	public void setCrtDtm(Date crtDtm) {
		this.crtDtm = crtDtm;
	}

	public Date getModifyDtm() {
		return modifyDtm;
	}

	public void setModifyDtm(Date modifyDtm) {
		this.modifyDtm = modifyDtm;
	}

	public Short getMemberType() {
		return memberType;
	}

	public void setMemberType(Short memberType) {
		this.memberType = memberType;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Short getAttribute1() {
		return attribute1;
	}

	public void setAttribute1(Short attribute1) {
		this.attribute1 = attribute1;
	}

	public String getAttribute2() {
		return attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	public String getAttribute3() {
		return attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	public String getAttribute4() {
		return attribute4;
	}

	public void setAttribute4(String attribute4) {
		this.attribute4 = attribute4;
	}

	public String getAttribute5() {
		return attribute5;
	}

	public void setAttribute5(String attribute5) {
		this.attribute5 = attribute5;
	}

	public String getAttribute6() {
		return attribute6;
	}

	public void setAttribute6(String attribute6) {
		this.attribute6 = attribute6;
	}

}