package com.we.repay.dao.user;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.we.repay.dto.draw.QueryRandomDrawReqDTO;
import com.we.repay.dto.user.QueryWxAccountRespDTO;
import com.we.repay.dto.user.WxAccountLoginReqDTO;
import com.we.repay.dto.user.WxAccountReqDTO;
import com.we.repay.dto.user.WxAccountRespDTO;
import com.we.repay.po.user.WxAccount;
import com.we.repay.po.user.WxAccountCriteria;

public interface WxAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int countByExample(WxAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int deleteByExample(WxAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int deleteByPrimaryKey(Long waId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int insert(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int insertSelective(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    List<WxAccount> selectByExample(WxAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    WxAccount selectByPrimaryKey(Long waId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") WxAccount record, @Param("example") WxAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int updateByExample(@Param("record") WxAccount record, @Param("example") WxAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int updateByPrimaryKeySelective(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated Tue Sep 19 17:45:27 CST 2017
     */
    int updateByPrimaryKey(WxAccount record);
    
    /**
     * #####################################################################
     */
    
    public List<WxAccount> selectListSelective(WxAccount record);
    
    public List<WxAccount> selectPageSelective(WxAccountReqDTO wxAccountReqDTO);
    
    public int selectPageCountSelective(WxAccountReqDTO wxAccountReqDTO);
    
    public WxAccount selectByMpOpenId(@Param("mpOpenId")String mpOpenId);
    
    public WxAccount login(WxAccountLoginReqDTO wxAccountLoginReqDTO);
    
    public long queryMaxCCid();
    
    public List<WxAccount> selectWxAccountList();
    
    public List<WxAccount> selectRandomDraw();
    
    public List<WxAccountRespDTO> selectByYear(@Param("year")String year);
    
    public List<QueryWxAccountRespDTO> selectRandomDrawByRdId(QueryRandomDrawReqDTO queryRandomDrawReqDTO);
}