package com.we.repay.dao.draw;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.we.repay.dto.draw.ModifyRandomDrawReqDTO;
import com.we.repay.dto.draw.QueryRandomDrawReqDTO;
import com.we.repay.dto.draw.RandomDrawReqDTO;
import com.we.repay.po.draw.RandomDraw;
import com.we.repay.po.draw.RandomDrawCriteria;

public interface RandomDrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int countByExample(RandomDrawCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int deleteByExample(RandomDrawCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int deleteByPrimaryKey(Long rdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int insert(RandomDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int insertSelective(RandomDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    List<RandomDraw> selectByExample(RandomDrawCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    RandomDraw selectByPrimaryKey(Long rdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") RandomDraw record, @Param("example") RandomDrawCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int updateByExample(@Param("record") RandomDraw record, @Param("example") RandomDrawCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int updateByPrimaryKeySelective(RandomDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    int updateByPrimaryKey(RandomDraw record);
    
    /**
     * ##################################################################
     */
    
    public List<RandomDraw> selectListSelective(RandomDraw record);
    
    public int updateByIdList(ModifyRandomDrawReqDTO modifyRandomDrawReqDTO);
    
    public List<RandomDraw> selectPageSelective(RandomDrawReqDTO randomDrawReqDTO);
    
    public int selectPageCountSelective(RandomDrawReqDTO randomDrawReqDTO);
    
    public int selectAttribute1Max();
    
    public List<RandomDraw> selectByRdIdList(QueryRandomDrawReqDTO queryRandomDrawReqDTO);
    
}