package com.we.repay.po.draw;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RandomDrawCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public RandomDrawCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRdIdIsNull() {
            addCriterion("rd_id is null");
            return (Criteria) this;
        }

        public Criteria andRdIdIsNotNull() {
            addCriterion("rd_id is not null");
            return (Criteria) this;
        }

        public Criteria andRdIdEqualTo(Long value) {
            addCriterion("rd_id =", value, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdNotEqualTo(Long value) {
            addCriterion("rd_id <>", value, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdGreaterThan(Long value) {
            addCriterion("rd_id >", value, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("rd_id >=", value, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdLessThan(Long value) {
            addCriterion("rd_id <", value, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdLessThanOrEqualTo(Long value) {
            addCriterion("rd_id <=", value, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdIn(List<Long> values) {
            addCriterion("rd_id in", values, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdNotIn(List<Long> values) {
            addCriterion("rd_id not in", values, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdBetween(Long value1, Long value2) {
            addCriterion("rd_id between", value1, value2, "rdId");
            return (Criteria) this;
        }

        public Criteria andRdIdNotBetween(Long value1, Long value2) {
            addCriterion("rd_id not between", value1, value2, "rdId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNumberCodeIsNull() {
            addCriterion("number_code is null");
            return (Criteria) this;
        }

        public Criteria andNumberCodeIsNotNull() {
            addCriterion("number_code is not null");
            return (Criteria) this;
        }

        public Criteria andNumberCodeEqualTo(String value) {
            addCriterion("number_code =", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeNotEqualTo(String value) {
            addCriterion("number_code <>", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeGreaterThan(String value) {
            addCriterion("number_code >", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeGreaterThanOrEqualTo(String value) {
            addCriterion("number_code >=", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeLessThan(String value) {
            addCriterion("number_code <", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeLessThanOrEqualTo(String value) {
            addCriterion("number_code <=", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeLike(String value) {
            addCriterion("number_code like", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeNotLike(String value) {
            addCriterion("number_code not like", value, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeIn(List<String> values) {
            addCriterion("number_code in", values, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeNotIn(List<String> values) {
            addCriterion("number_code not in", values, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeBetween(String value1, String value2) {
            addCriterion("number_code between", value1, value2, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNumberCodeNotBetween(String value1, String value2) {
            addCriterion("number_code not between", value1, value2, "numberCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeIsNull() {
            addCriterion("no_prefix_code is null");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeIsNotNull() {
            addCriterion("no_prefix_code is not null");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeEqualTo(Integer value) {
            addCriterion("no_prefix_code =", value, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeNotEqualTo(Integer value) {
            addCriterion("no_prefix_code <>", value, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeGreaterThan(Integer value) {
            addCriterion("no_prefix_code >", value, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("no_prefix_code >=", value, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeLessThan(Integer value) {
            addCriterion("no_prefix_code <", value, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeLessThanOrEqualTo(Integer value) {
            addCriterion("no_prefix_code <=", value, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeIn(List<Integer> values) {
            addCriterion("no_prefix_code in", values, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeNotIn(List<Integer> values) {
            addCriterion("no_prefix_code not in", values, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeBetween(Integer value1, Integer value2) {
            addCriterion("no_prefix_code between", value1, value2, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andNoPrefixCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("no_prefix_code not between", value1, value2, "noPrefixCode");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelIsNull() {
            addCriterion("prize_level is null");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelIsNotNull() {
            addCriterion("prize_level is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelEqualTo(Short value) {
            addCriterion("prize_level =", value, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelNotEqualTo(Short value) {
            addCriterion("prize_level <>", value, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelGreaterThan(Short value) {
            addCriterion("prize_level >", value, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelGreaterThanOrEqualTo(Short value) {
            addCriterion("prize_level >=", value, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelLessThan(Short value) {
            addCriterion("prize_level <", value, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelLessThanOrEqualTo(Short value) {
            addCriterion("prize_level <=", value, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelIn(List<Short> values) {
            addCriterion("prize_level in", values, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelNotIn(List<Short> values) {
            addCriterion("prize_level not in", values, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelBetween(Short value1, Short value2) {
            addCriterion("prize_level between", value1, value2, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeLevelNotBetween(Short value1, Short value2) {
            addCriterion("prize_level not between", value1, value2, "prizeLevel");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmIsNull() {
            addCriterion("prize_dtm is null");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmIsNotNull() {
            addCriterion("prize_dtm is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmEqualTo(Date value) {
            addCriterion("prize_dtm =", value, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmNotEqualTo(Date value) {
            addCriterion("prize_dtm <>", value, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmGreaterThan(Date value) {
            addCriterion("prize_dtm >", value, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("prize_dtm >=", value, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmLessThan(Date value) {
            addCriterion("prize_dtm <", value, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmLessThanOrEqualTo(Date value) {
            addCriterion("prize_dtm <=", value, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmIn(List<Date> values) {
            addCriterion("prize_dtm in", values, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmNotIn(List<Date> values) {
            addCriterion("prize_dtm not in", values, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmBetween(Date value1, Date value2) {
            addCriterion("prize_dtm between", value1, value2, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andPrizeDtmNotBetween(Date value1, Date value2) {
            addCriterion("prize_dtm not between", value1, value2, "prizeDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmIsNull() {
            addCriterion("crt_dtm is null");
            return (Criteria) this;
        }

        public Criteria andCrtDtmIsNotNull() {
            addCriterion("crt_dtm is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDtmEqualTo(Date value) {
            addCriterion("crt_dtm =", value, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmNotEqualTo(Date value) {
            addCriterion("crt_dtm <>", value, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmGreaterThan(Date value) {
            addCriterion("crt_dtm >", value, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("crt_dtm >=", value, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmLessThan(Date value) {
            addCriterion("crt_dtm <", value, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmLessThanOrEqualTo(Date value) {
            addCriterion("crt_dtm <=", value, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmIn(List<Date> values) {
            addCriterion("crt_dtm in", values, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmNotIn(List<Date> values) {
            addCriterion("crt_dtm not in", values, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmBetween(Date value1, Date value2) {
            addCriterion("crt_dtm between", value1, value2, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andCrtDtmNotBetween(Date value1, Date value2) {
            addCriterion("crt_dtm not between", value1, value2, "crtDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmIsNull() {
            addCriterion("modify_dtm is null");
            return (Criteria) this;
        }

        public Criteria andModifyDtmIsNotNull() {
            addCriterion("modify_dtm is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDtmEqualTo(Date value) {
            addCriterion("modify_dtm =", value, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmNotEqualTo(Date value) {
            addCriterion("modify_dtm <>", value, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmGreaterThan(Date value) {
            addCriterion("modify_dtm >", value, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_dtm >=", value, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmLessThan(Date value) {
            addCriterion("modify_dtm <", value, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmLessThanOrEqualTo(Date value) {
            addCriterion("modify_dtm <=", value, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmIn(List<Date> values) {
            addCriterion("modify_dtm in", values, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmNotIn(List<Date> values) {
            addCriterion("modify_dtm not in", values, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmBetween(Date value1, Date value2) {
            addCriterion("modify_dtm between", value1, value2, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andModifyDtmNotBetween(Date value1, Date value2) {
            addCriterion("modify_dtm not between", value1, value2, "modifyDtm");
            return (Criteria) this;
        }

        public Criteria andMemberTypeIsNull() {
            addCriterion("member_type is null");
            return (Criteria) this;
        }

        public Criteria andMemberTypeIsNotNull() {
            addCriterion("member_type is not null");
            return (Criteria) this;
        }

        public Criteria andMemberTypeEqualTo(Short value) {
            addCriterion("member_type =", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotEqualTo(Short value) {
            addCriterion("member_type <>", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeGreaterThan(Short value) {
            addCriterion("member_type >", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("member_type >=", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeLessThan(Short value) {
            addCriterion("member_type <", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeLessThanOrEqualTo(Short value) {
            addCriterion("member_type <=", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeIn(List<Short> values) {
            addCriterion("member_type in", values, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotIn(List<Short> values) {
            addCriterion("member_type not in", values, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeBetween(Short value1, Short value2) {
            addCriterion("member_type between", value1, value2, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotBetween(Short value1, Short value2) {
            addCriterion("member_type not between", value1, value2, "memberType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNull() {
            addCriterion("attribute1 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNotNull() {
            addCriterion("attribute1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute1EqualTo(String value) {
            addCriterion("attribute1 =", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotEqualTo(String value) {
            addCriterion("attribute1 <>", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThan(String value) {
            addCriterion("attribute1 >", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
            addCriterion("attribute1 >=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThan(String value) {
            addCriterion("attribute1 <", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThanOrEqualTo(String value) {
            addCriterion("attribute1 <=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Like(String value) {
            addCriterion("attribute1 like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotLike(String value) {
            addCriterion("attribute1 not like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1In(List<String> values) {
            addCriterion("attribute1 in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotIn(List<String> values) {
            addCriterion("attribute1 not in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Between(String value1, String value2) {
            addCriterion("attribute1 between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotBetween(String value1, String value2) {
            addCriterion("attribute1 not between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNull() {
            addCriterion("attribute2 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNotNull() {
            addCriterion("attribute2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute2EqualTo(String value) {
            addCriterion("attribute2 =", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotEqualTo(String value) {
            addCriterion("attribute2 <>", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThan(String value) {
            addCriterion("attribute2 >", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
            addCriterion("attribute2 >=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThan(String value) {
            addCriterion("attribute2 <", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThanOrEqualTo(String value) {
            addCriterion("attribute2 <=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Like(String value) {
            addCriterion("attribute2 like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotLike(String value) {
            addCriterion("attribute2 not like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2In(List<String> values) {
            addCriterion("attribute2 in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotIn(List<String> values) {
            addCriterion("attribute2 not in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Between(String value1, String value2) {
            addCriterion("attribute2 between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotBetween(String value1, String value2) {
            addCriterion("attribute2 not between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNull() {
            addCriterion("attribute3 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNotNull() {
            addCriterion("attribute3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute3EqualTo(String value) {
            addCriterion("attribute3 =", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotEqualTo(String value) {
            addCriterion("attribute3 <>", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThan(String value) {
            addCriterion("attribute3 >", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
            addCriterion("attribute3 >=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThan(String value) {
            addCriterion("attribute3 <", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThanOrEqualTo(String value) {
            addCriterion("attribute3 <=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Like(String value) {
            addCriterion("attribute3 like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotLike(String value) {
            addCriterion("attribute3 not like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3In(List<String> values) {
            addCriterion("attribute3 in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotIn(List<String> values) {
            addCriterion("attribute3 not in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Between(String value1, String value2) {
            addCriterion("attribute3 between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotBetween(String value1, String value2) {
            addCriterion("attribute3 not between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNull() {
            addCriterion("attribute4 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNotNull() {
            addCriterion("attribute4 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute4EqualTo(String value) {
            addCriterion("attribute4 =", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotEqualTo(String value) {
            addCriterion("attribute4 <>", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThan(String value) {
            addCriterion("attribute4 >", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThanOrEqualTo(String value) {
            addCriterion("attribute4 >=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThan(String value) {
            addCriterion("attribute4 <", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThanOrEqualTo(String value) {
            addCriterion("attribute4 <=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Like(String value) {
            addCriterion("attribute4 like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotLike(String value) {
            addCriterion("attribute4 not like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4In(List<String> values) {
            addCriterion("attribute4 in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotIn(List<String> values) {
            addCriterion("attribute4 not in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Between(String value1, String value2) {
            addCriterion("attribute4 between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotBetween(String value1, String value2) {
            addCriterion("attribute4 not between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNull() {
            addCriterion("attribute5 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNotNull() {
            addCriterion("attribute5 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute5EqualTo(String value) {
            addCriterion("attribute5 =", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotEqualTo(String value) {
            addCriterion("attribute5 <>", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThan(String value) {
            addCriterion("attribute5 >", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThanOrEqualTo(String value) {
            addCriterion("attribute5 >=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThan(String value) {
            addCriterion("attribute5 <", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThanOrEqualTo(String value) {
            addCriterion("attribute5 <=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Like(String value) {
            addCriterion("attribute5 like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotLike(String value) {
            addCriterion("attribute5 not like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5In(List<String> values) {
            addCriterion("attribute5 in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotIn(List<String> values) {
            addCriterion("attribute5 not in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Between(String value1, String value2) {
            addCriterion("attribute5 between", value1, value2, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotBetween(String value1, String value2) {
            addCriterion("attribute5 not between", value1, value2, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute6IsNull() {
            addCriterion("attribute6 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute6IsNotNull() {
            addCriterion("attribute6 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute6EqualTo(String value) {
            addCriterion("attribute6 =", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotEqualTo(String value) {
            addCriterion("attribute6 <>", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6GreaterThan(String value) {
            addCriterion("attribute6 >", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6GreaterThanOrEqualTo(String value) {
            addCriterion("attribute6 >=", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6LessThan(String value) {
            addCriterion("attribute6 <", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6LessThanOrEqualTo(String value) {
            addCriterion("attribute6 <=", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6Like(String value) {
            addCriterion("attribute6 like", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotLike(String value) {
            addCriterion("attribute6 not like", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6In(List<String> values) {
            addCriterion("attribute6 in", values, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotIn(List<String> values) {
            addCriterion("attribute6 not in", values, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6Between(String value1, String value2) {
            addCriterion("attribute6 between", value1, value2, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotBetween(String value1, String value2) {
            addCriterion("attribute6 not between", value1, value2, "attribute6");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table random_draw
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 15 15:05:23 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}