package com.we.repay.po.draw;

import java.util.Date;

public class RandomDraw {
    /**
     * 主键ID
     */
    private Long rdId;

    /**
     * 会员姓名
     */
    private String name;

    /**
     * 会员编号
     */
    private String numberCode;

    /**
     * 无前辍编号
     */
    private Integer noPrefixCode;

    /**
     * 中奖级别 -1 未中奖 0 未抽奖 1 是一等奖 2 是二等奖 3 三等奖 4 四等奖 5 五等奖 6 六等奖
     */
    private Short prizeLevel;

    /**
     * 中奖时间
     */
    private Date prizeDtm;

    /**
     * 创建时间
     */
    private Date crtDtm;

    /**
     * 更新时间
     */
    private Date modifyDtm;

    /**
     * 会员类型
     */
    private Short memberType;

    /**
     * 会员ID
     */
    private Long userId;

    /**
     * 抽奖资格状态  1 正常 0 异常（没有资格抽奖）
     */
    private Short status;

    /**
     * 抽奖批次
     */
    private Short attribute1;

    /**
     * 会员注册的年份
     */
    private String attribute2;

    /**
     * 批次号
     */
    private String attribute3;

    /**
     * 预留字段4
     */
    private String attribute4;

    /**
     * 预留字段5
     */
    private String attribute5;

    /**
     * 预留字段6
     */
    private String attribute6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.rd_id
     *
     * @return the value of random_draw.rd_id
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Long getRdId() {
        return rdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.rd_id
     *
     * @param rdId the value for random_draw.rd_id
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setRdId(Long rdId) {
        this.rdId = rdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.name
     *
     * @return the value of random_draw.name
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.name
     *
     * @param name the value for random_draw.name
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.number_code
     *
     * @return the value of random_draw.number_code
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getNumberCode() {
        return numberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.number_code
     *
     * @param numberCode the value for random_draw.number_code
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setNumberCode(String numberCode) {
        this.numberCode = numberCode == null ? null : numberCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.no_prefix_code
     *
     * @return the value of random_draw.no_prefix_code
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Integer getNoPrefixCode() {
        return noPrefixCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.no_prefix_code
     *
     * @param noPrefixCode the value for random_draw.no_prefix_code
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setNoPrefixCode(Integer noPrefixCode) {
        this.noPrefixCode = noPrefixCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.prize_level
     *
     * @return the value of random_draw.prize_level
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Short getPrizeLevel() {
        return prizeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.prize_level
     *
     * @param prizeLevel the value for random_draw.prize_level
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setPrizeLevel(Short prizeLevel) {
        this.prizeLevel = prizeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.prize_dtm
     *
     * @return the value of random_draw.prize_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Date getPrizeDtm() {
        return prizeDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.prize_dtm
     *
     * @param prizeDtm the value for random_draw.prize_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setPrizeDtm(Date prizeDtm) {
        this.prizeDtm = prizeDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.crt_dtm
     *
     * @return the value of random_draw.crt_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Date getCrtDtm() {
        return crtDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.crt_dtm
     *
     * @param crtDtm the value for random_draw.crt_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setCrtDtm(Date crtDtm) {
        this.crtDtm = crtDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.modify_dtm
     *
     * @return the value of random_draw.modify_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Date getModifyDtm() {
        return modifyDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.modify_dtm
     *
     * @param modifyDtm the value for random_draw.modify_dtm
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setModifyDtm(Date modifyDtm) {
        this.modifyDtm = modifyDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.member_type
     *
     * @return the value of random_draw.member_type
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Short getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.member_type
     *
     * @param memberType the value for random_draw.member_type
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setMemberType(Short memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.user_id
     *
     * @return the value of random_draw.user_id
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.user_id
     *
     * @param userId the value for random_draw.user_id
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.status
     *
     * @return the value of random_draw.status
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.status
     *
     * @param status the value for random_draw.status
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.attribute1
     *
     * @return the value of random_draw.attribute1
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public Short getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.attribute1
     *
     * @param attribute1 the value for random_draw.attribute1
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setAttribute1(Short attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.attribute2
     *
     * @return the value of random_draw.attribute2
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.attribute2
     *
     * @param attribute2 the value for random_draw.attribute2
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.attribute3
     *
     * @return the value of random_draw.attribute3
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.attribute3
     *
     * @param attribute3 the value for random_draw.attribute3
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.attribute4
     *
     * @return the value of random_draw.attribute4
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.attribute4
     *
     * @param attribute4 the value for random_draw.attribute4
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.attribute5
     *
     * @return the value of random_draw.attribute5
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.attribute5
     *
     * @param attribute5 the value for random_draw.attribute5
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5 == null ? null : attribute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_draw.attribute6
     *
     * @return the value of random_draw.attribute6
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_draw.attribute6
     *
     * @param attribute6 the value for random_draw.attribute6
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6 == null ? null : attribute6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RandomDraw other = (RandomDraw) that;
        return (this.getRdId() == null ? other.getRdId() == null : this.getRdId().equals(other.getRdId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNumberCode() == null ? other.getNumberCode() == null : this.getNumberCode().equals(other.getNumberCode()))
            && (this.getNoPrefixCode() == null ? other.getNoPrefixCode() == null : this.getNoPrefixCode().equals(other.getNoPrefixCode()))
            && (this.getPrizeLevel() == null ? other.getPrizeLevel() == null : this.getPrizeLevel().equals(other.getPrizeLevel()))
            && (this.getPrizeDtm() == null ? other.getPrizeDtm() == null : this.getPrizeDtm().equals(other.getPrizeDtm()))
            && (this.getCrtDtm() == null ? other.getCrtDtm() == null : this.getCrtDtm().equals(other.getCrtDtm()))
            && (this.getModifyDtm() == null ? other.getModifyDtm() == null : this.getModifyDtm().equals(other.getModifyDtm()))
            && (this.getMemberType() == null ? other.getMemberType() == null : this.getMemberType().equals(other.getMemberType()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()))
            && (this.getAttribute4() == null ? other.getAttribute4() == null : this.getAttribute4().equals(other.getAttribute4()))
            && (this.getAttribute5() == null ? other.getAttribute5() == null : this.getAttribute5().equals(other.getAttribute5()))
            && (this.getAttribute6() == null ? other.getAttribute6() == null : this.getAttribute6().equals(other.getAttribute6()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table random_draw
     *
     * @mbggenerated Fri Dec 15 15:05:23 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRdId() == null) ? 0 : getRdId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNumberCode() == null) ? 0 : getNumberCode().hashCode());
        result = prime * result + ((getNoPrefixCode() == null) ? 0 : getNoPrefixCode().hashCode());
        result = prime * result + ((getPrizeLevel() == null) ? 0 : getPrizeLevel().hashCode());
        result = prime * result + ((getPrizeDtm() == null) ? 0 : getPrizeDtm().hashCode());
        result = prime * result + ((getCrtDtm() == null) ? 0 : getCrtDtm().hashCode());
        result = prime * result + ((getModifyDtm() == null) ? 0 : getModifyDtm().hashCode());
        result = prime * result + ((getMemberType() == null) ? 0 : getMemberType().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        result = prime * result + ((getAttribute4() == null) ? 0 : getAttribute4().hashCode());
        result = prime * result + ((getAttribute5() == null) ? 0 : getAttribute5().hashCode());
        result = prime * result + ((getAttribute6() == null) ? 0 : getAttribute6().hashCode());
        return result;
    }
}