package com.we.repay.dao.repay;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.we.repay.dto.repay.QueryAmoutSumReqDTO;
import com.we.repay.dto.repay.RepayRecordReqDTO;
import com.we.repay.po.repay.RepayRecord;
import com.we.repay.po.repay.RepayRecordCriteria;

public interface RepayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int countByExample(RepayRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int deleteByExample(RepayRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int deleteByPrimaryKey(Long wrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int insert(RepayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int insertSelective(RepayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    List<RepayRecord> selectByExample(RepayRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    RepayRecord selectByPrimaryKey(Long wrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") RepayRecord record, @Param("example") RepayRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int updateByExample(@Param("record") RepayRecord record, @Param("example") RepayRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int updateByPrimaryKeySelective(RepayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    int updateByPrimaryKey(RepayRecord record);
    
    /**
     * #################################################
     */
    
    public List<RepayRecord> selectListSelective(RepayRecord record);
    
    public List<RepayRecord> selectPageSelective(RepayRecordReqDTO record);
    
    public int selectPageCountSelective(RepayRecordReqDTO record);
    
    public int updateByOrdIdSelective(RepayRecord record);
    
    public List<RepayRecord> selectAmountSum(QueryAmoutSumReqDTO queryAmoutSumReqDTO);
    
    public int selectAmountSumCount(QueryAmoutSumReqDTO queryAmoutSumReqDTO);
}