package com.we.repay.po.repay;

import java.util.Date;

public class RepayRecord {
    /**
     * 主键ID
     */
    private Long wrId;

    /**
     * 微信账号ID
     */
    private Long waId;

    /**
     * 订单ID
     */
    private String ordId;

    /**
     * 微信账号标识ID
     */
    private String wxOpenId;

    /**
     * 状态:0--待支付，1-交易成功,2-交易失败，3-转入退款，4-已关闭，5-已撤销，6-用户支付中
     */
    private Short status;

    /**
     * 多状态查询
     */
    private String instatus;
    
    /**
     * 金额
     */
    private Float amount;

    /**
     * 创建时间
     */
    private Date createDtm;

    /**
     * 更新时间
     */
    private Date updateDtm;

    /**
     * 支付人
     */
    private String payMan;

    /**
     * 预留字段1
     */
    private String attribute1;

    /**
     * 预留字段2
     */
    private String attribute2;

    /**
     * 预留字段3
     */
    private String attribute3;
    
    /**
     * 预留字段4
     */
    private String attribute4;
    
    /**
     * 真实姓名
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.wr_id
     *
     * @return the value of repay_record.wr_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public Long getWrId() {
        return wrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.wr_id
     *
     * @param wrId the value for repay_record.wr_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setWrId(Long wrId) {
        this.wrId = wrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.wa_id
     *
     * @return the value of repay_record.wa_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public Long getWaId() {
        return waId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.wa_id
     *
     * @param waId the value for repay_record.wa_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setWaId(Long waId) {
        this.waId = waId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.ord_id
     *
     * @return the value of repay_record.ord_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public String getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.ord_id
     *
     * @param ordId the value for repay_record.ord_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setOrdId(String ordId) {
        this.ordId = ordId == null ? null : ordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.wx_open_id
     *
     * @return the value of repay_record.wx_open_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.wx_open_id
     *
     * @param wxOpenId the value for repay_record.wx_open_id
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.status
     *
     * @return the value of repay_record.status
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.status
     *
     * @param status the value for repay_record.status
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    
    public String getInstatus() {
		return instatus;
	}

	public void setInstatus(String instatus) {
		this.instatus = instatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.amount
     *
     * @return the value of repay_record.amount
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.amount
     *
     * @param amount the value for repay_record.amount
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.create_dtm
     *
     * @return the value of repay_record.create_dtm
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public Date getCreateDtm() {
        return createDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.create_dtm
     *
     * @param createDtm the value for repay_record.create_dtm
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setCreateDtm(Date createDtm) {
        this.createDtm = createDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.update_dtm
     *
     * @return the value of repay_record.update_dtm
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public Date getUpdateDtm() {
        return updateDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.update_dtm
     *
     * @param updateDtm the value for repay_record.update_dtm
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setUpdateDtm(Date updateDtm) {
        this.updateDtm = updateDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.pay_man
     *
     * @return the value of repay_record.pay_man
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public String getPayMan() {
        return payMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.pay_man
     *
     * @param payMan the value for repay_record.pay_man
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setPayMan(String payMan) {
        this.payMan = payMan == null ? null : payMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.attribute1
     *
     * @return the value of repay_record.attribute1
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.attribute1
     *
     * @param attribute1 the value for repay_record.attribute1
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.attribute2
     *
     * @return the value of repay_record.attribute2
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.attribute2
     *
     * @param attribute2 the value for repay_record.attribute2
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repay_record.attribute3
     *
     * @return the value of repay_record.attribute3
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repay_record.attribute3
     *
     * @param attribute3 the value for repay_record.attribute3
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }
    
    

    public String getAttribute4() {
		return attribute4;
	}

	public void setAttribute4(String attribute4) {
		this.attribute4 = attribute4;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RepayRecord other = (RepayRecord) that;
        return (this.getWrId() == null ? other.getWrId() == null : this.getWrId().equals(other.getWrId()))
            && (this.getWaId() == null ? other.getWaId() == null : this.getWaId().equals(other.getWaId()))
            && (this.getOrdId() == null ? other.getOrdId() == null : this.getOrdId().equals(other.getOrdId()))
            && (this.getWxOpenId() == null ? other.getWxOpenId() == null : this.getWxOpenId().equals(other.getWxOpenId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCreateDtm() == null ? other.getCreateDtm() == null : this.getCreateDtm().equals(other.getCreateDtm()))
            && (this.getUpdateDtm() == null ? other.getUpdateDtm() == null : this.getUpdateDtm().equals(other.getUpdateDtm()))
            && (this.getPayMan() == null ? other.getPayMan() == null : this.getPayMan().equals(other.getPayMan()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()))
            && (this.getAttribute4() == null ? other.getAttribute4() == null : this.getAttribute4().equals(other.getAttribute4()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repay_record
     *
     * @mbggenerated Wed Sep 20 15:13:39 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWrId() == null) ? 0 : getWrId().hashCode());
        result = prime * result + ((getWaId() == null) ? 0 : getWaId().hashCode());
        result = prime * result + ((getOrdId() == null) ? 0 : getOrdId().hashCode());
        result = prime * result + ((getWxOpenId() == null) ? 0 : getWxOpenId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCreateDtm() == null) ? 0 : getCreateDtm().hashCode());
        result = prime * result + ((getUpdateDtm() == null) ? 0 : getUpdateDtm().hashCode());
        result = prime * result + ((getPayMan() == null) ? 0 : getPayMan().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        result = prime * result + ((getAttribute4() == null) ? 0 : getAttribute4().hashCode());
        return result;
    }

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}
}