package com.we.repay.po.repay;

import java.util.Date;

import com.we.repay.dto.QueryReqDTO;

@SuppressWarnings("serial")
public class YearPayRecord extends QueryReqDTO{
    /**
     * 主键
     */
    private Long id;
    
    /**
     * 年份
     */
    private String year;

    /**
     * 用户名
     */
    private String realName;

    /**
     * 用户编号
     */
    private String userNumber;

    /**
     * 年费
     */
    private Float yearAnnualFee =  null;

    /**
     * 支付时间
     */
    private Date payTime;

    /**
     * -1:终生会员；1:已支付，2：未支付，3：未完全支付
     */
    private Short payStatus;

    /**
     * 预留字段1
     */
    private String attribute1;

    /**
     * 预留字段2
     */
    private String attribute2;

    /**
     * 预留字段3
     */
    private String attribute3;
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_pay_record.id
     *
     * @param id the value for year_pay_record.id
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_pay_record.real_name
     *
     * @return the value of year_pay_record.real_name
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_pay_record.real_name
     *
     * @param realName the value for year_pay_record.real_name
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_pay_record.user_number
     *
     * @return the value of year_pay_record.user_number
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_pay_record.user_number
     *
     * @param userNumber the value for year_pay_record.user_number
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_pay_record.year_annual_fee
     *
     * @return the value of year_pay_record.year_annual_fee
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public Float getYearAnnualFee() {
        return yearAnnualFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_pay_record.year_annual_fee
     *
     * @param yearAnnualFee the value for year_pay_record.year_annual_fee
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public void setYearAnnualFee(Float yearAnnualFee) {
        this.yearAnnualFee = yearAnnualFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_pay_record.pay_time
     *
     * @return the value of year_pay_record.pay_time
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_pay_record.pay_time
     *
     * @param payTime the value for year_pay_record.pay_time
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_pay_record.pay_status
     *
     * @return the value of year_pay_record.pay_status
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_pay_record.pay_status
     *
     * @param payStatus the value for year_pay_record.pay_status
     *
     * @mbggenerated Thu Nov 16 16:50:42 CST 2017
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getAttribute1() {
		return attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	public String getAttribute2() {
		return attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	public String getAttribute3() {
		return attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((payStatus == null) ? 0 : payStatus.hashCode());
		result = prime * result + ((payTime == null) ? 0 : payTime.hashCode());
		result = prime * result
				+ ((realName == null) ? 0 : realName.hashCode());
		result = prime * result
				+ ((userNumber == null) ? 0 : userNumber.hashCode());
		result = prime * result + ((year == null) ? 0 : year.hashCode());
		result = prime * result + Float.floatToIntBits(yearAnnualFee);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		YearPayRecord other = (YearPayRecord) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (payStatus == null) {
			if (other.payStatus != null)
				return false;
		} else if (!payStatus.equals(other.payStatus))
			return false;
		if (payTime == null) {
			if (other.payTime != null)
				return false;
		} else if (!payTime.equals(other.payTime))
			return false;
		if (realName == null) {
			if (other.realName != null)
				return false;
		} else if (!realName.equals(other.realName))
			return false;
		if (userNumber == null) {
			if (other.userNumber != null)
				return false;
		} else if (!userNumber.equals(other.userNumber))
			return false;
		if (year == null) {
			if (other.year != null)
				return false;
		} else if (!year.equals(other.year))
			return false;
		if (Float.floatToIntBits(yearAnnualFee) != Float
				.floatToIntBits(other.yearAnnualFee))
			return false;
		return true;
	}

   
}